
version: "3"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./:/docs
    restart: always
    ports:
      - "8888:8080"
    environment:
      SWAGGER_JSON: /docs/swagger.json

  