const ERROR_MESSAGES = {
    "1": "WIALON_INVALIDSESSION",
    "2": "WIALON_INVALIDSERVICE",
    "3": "WIALON_INVALIDRESPONSE",
    "4": "WIALON_INVALIDREQUEST",
    "5": "WIALON_ERROREXECUTEREQUEST",
    "6": "WIALON_UNKNOWNERROR",
    "7": "WIALON_ACCESSDENIED",
    "8": "WIALON_INVALIDNAMEPASSWORD",
    "9": "WIALON_AUTHSERVICENOTAVAILABLE",
    "10": "WIALON_LIMITREQUEST",
    "14": "WIALON_ERRORBILLING",
    "1001": "WIALON_EMPTYMESSAGE"
}

export { ERROR_MESSAGES };